src/CsvHelper.Tests/CsvWriterFormatTests.cs
src/CsvHelper/CsvWriter.cs

I expected TrimFields to act in the same way as the reader when writing

Add Trim Field to CsvWriter

---

src/CsvHelper/CsvHelper.csproj
src/CsvHelper/CsvWriter.cs

After a rebase and test, I discovered a index OOB exception. Added a check for null/empty strings to avoid this on empty fields.

add null/empty string check

---

README.markdown

Added missing word so unit testing guideline makes sense

Tiny grammar fix to README

---

src/CsvHelper.Tests/CsvHelper.Tests.csproj
src/CsvHelper.Tests/TypeConversion/ByteArrayConverterTests.cs
src/CsvHelper/TypeConversion/ByteArrayConverter.cs

Definitely open to any changes you or the community can think of

Add ByteArrayConverter with some common formatting options

---

index.md

I believe this is the method that's being referred to.

Update runtime mapping reference

---

src/CsvHelper.Tests/CsvHelper.Tests.csproj
src/CsvHelper/Configuration/CsvClassMapCollection.cs
src/CsvHelper/CsvHelper.csproj
src/CsvHelper/CsvWriter.cs

fix identical conditional expressions

---

pages/writing.md

Fixed typo in injection warning

Fixed typo

---

src/CsvHelper/TypeConversion/DefaultTypeConverter.cs

You forgot to actually use your extended message which was added for #782.

Fixed TypeConverterException message

---

src/CsvHelper/CsvWriter.cs
src/CsvHelper/Expressions/RecordCreatorFactory.cs
src/CsvHelper/Expressions/RecordHydrator.cs
src/CsvHelper/Expressions/RecordManager.cs
src/CsvHelper/Expressions/RecordWriter.cs
src/CsvHelper/Expressions/RecordWriterFactory.cs

Use ObjectResolver to create internal classes

---

src/CsvHelper/Configuration/Configuration.cs

Fix documentation typo

---

pages/type-conversion.md

Fixes a typo and corrects the placing of an in-line code quote.

Fix typos.

---

src/CsvHelper/CsvFieldReader.tt
src/CsvHelper/CsvParser.tt

Apparently 05292efc8a6f6107837c53e482f604753de9ac56 has broken T4 templates.

T4 Templates fix for CsvFieldReader and CsvParser

---

src/CsvHelper.Tests/CsvReaderMappingTests.cs
src/CsvHelper/Configuration/MemberMapData.cs
src/CsvHelper/Configuration/MemberMap`1.cs
src/CsvHelper/CsvReader.cs
src/CsvHelper/Expressions/ExpressionManager.cs

Adding IsOptional mapping option

---

src/CsvHelper/CsvSerializer.cs

Write line break always as \r\n to comply with ISO4180.

---

tests/CsvHelper.Tests/AutoMapping/AutoMappingTests.cs

just another unit test making sure things work correct with csv files typically used in german culture (especially floating point)

add unit test for floating point types (auto mapping, culture de-DE)

---

src/CsvHelper.Tests/Writing/DoubleEdgeTest.cs
src/CsvHelper/TypeConversion/DoubleConverter.cs

Add test and fix for reading double max/min values.

Fix double max and min values reader

---

src/CsvHelper/ReflectionHelper.cs
tests/CsvHelper.Tests/CsvHelper.Tests.csproj
tests/CsvHelper.Tests/Reflection/CreateInstanceTests.cs

Resolves #1486 
Related Commit: https://github.com/JoshClose/CsvHelper/commit/7cb429d2073c68c36536cea38fbb5b01bbd95080#diff-e385d64a5a5ec66688e371e64cf61077

fix reflection helper issue #1486

---

src/CsvHelper/CsvParser.cs
tests/CsvHelper.Tests/Parsing/ByteCountTests.cs
tests/CsvHelper.Tests/Parsing/CharCountTests.cs

Fix Trim mode

---

docs/examples/configuration/class-maps/mapping-by-index/index.html

Fix omitted argument in docs

---

src/CsvHelper/CsvReader.cs
tests/CsvHelper.Tests/CsvReaderTests.cs

Fix TryGetField exception

---

src/CsvHelper/CsvDataReader.cs
tests/CsvHelper.Tests/DataTableTests/CsvDataReaderTests.cs

Addresses https://github.com/JoshClose/CsvHelper/issues/1944

Make GetDataTypeName respect overridden schema data types

---

src/CsvHelper/Configuration/MemberMap`1.cs
tests/CsvHelper.Tests/CsvReaderMappingTests.cs
tests/CsvHelper.Tests/CsvWriterMappingTests.cs

Fixes #1927
See #1927 for details

Fix issue with static functions in MemberMap.Convert

---

src/CsvHelper/TypeConversion/DateTimeConverter.cs
tests/CsvHelper.Tests/TypeConversion/DateTimeConverterTests.cs

Fix Parsing DateTime field results in System.Exception, not CsvHelperException

---

src/CsvHelper/CsvParser.cs

Check CsvParser parameters for null

---

src/CsvHelper/Configuration/ConfigurationFunctions.cs
src/CsvHelper/CsvDataReader.cs
src/CsvHelper/CsvHelper.csproj
src/CsvHelper/Expressions/ObjectRecordWriter.cs
tests/CsvHelper.Tests/CsvHelper.Tests.csproj
tests/CsvHelper.Tests/CsvWriterMappingTests.cs
tests/CsvHelper.Tests/DataTableTests/CsvDataReaderTests.cs
tests/CsvHelper.Tests/Mocks/SerializerMock.cs

This fixes the typo I mentioned in https://github.com/JoshClose/CsvHelper/issues/1571 .
This is my first GitHub PR so let me know if I did anything wrong!  Thanks!

Fix typo in XML comment.

---

src/CsvHelper.Tests/Mappings/RuntimeMapping.cs
src/CsvHelper/Configuration/MemberMap.cs

MemberMap: relax Default and Constant type constraints to "assignable from"

---

src/CsvHelper.Website/input/examples/_directory.json
src/CsvHelper.Website/input/examples/type-conversion/custom-type-converter/index.md
src/CsvHelper.Website/input/examples/type-conversion/index.md
src/CsvHelper.Website/input/examples/type-conversion/type-converter-options/index.md

Added the documentation for the type converter options. Please have a look and let me know if something has to be changed. cheers!!

Add documentation for type converter options #397

---

docs/examples/prerequisites/using-and-dispose/index.html

A small fix in the documentation.

Fixed grammatical error in documentation.

---

src/CsvHelper/Configuration/ConfigurationFunctions.cs
tests/CsvHelper.Tests/Parsing/DetectDelimiterTests.cs

Fixed GetDelimiter issue with blank lines

---

src/CsvHelper/CsvReader.cs
tests/CsvHelper.Tests/CsvReaderTests.cs

Always update CsvReader.ColumnCount

---

src/CsvHelper/CsvDataReader.cs
src/CsvHelper/CsvReader.cs
tests/CsvHelper.Tests/DataTableTests/CsvDataReaderTests.cs

when there was no header record it would return an empty datatable with this change a table will be returned with generic header

HasHeaderRecord = False now loads Datatable

---

src/CsvHelper/CsvWriter.cs
tests/CsvHelper.Tests/CsvWriterTests.cs

Also write the header of the first non-null record rather than the last
fixes #2092

Add check for hasHeaderRecord in CsvWriter.WriteHeader(IEnumerable).
