src/CsvHelper.Tests/ExcelCompatibleTests.cs
src/CsvHelper/Configuration/CsvConfiguration.cs
src/CsvHelper/CsvSerializer.cs

When exporting a file strictly for use in Excel, it is sometimes desirable to use a special prefix on numeric strings to preserve leading zeros (e.g. for postal codes '00501'). This pull request supports that feature as a configuration parameter.

Allow preservation of numeric strings for Excel

---

src/CsvHelper/CsvWriter.cs
src/CsvHelper35.Tests/CsvWriterTests.cs

I've fixed the issue #349. Main idea is to use not the _real_ enumerable type (it can even be any nongeneric type implementing the `IEnumerable<T>`) but to extract the generic type we really care about - `IEnumerable<T>` and use its single generic argument we know of.
Please check my usage of generics and types - I am not sure whether such usage of `IEnumerable<T>` is supported by all platforms supported by CsvHelper itself.

Fix issue #349

---

src/CsvHelper.SpeedTests/Program.cs
src/CsvHelper.Tests/AutoMappingTests.cs
src/CsvHelper/Configuration/CsvClassMap.cs
src/CsvHelper/Configuration/CsvConfiguration.cs
src/CsvHelper/Configuration/CsvPropertyMapCollection.cs
src/CsvHelper/Configuration/CsvPropertyMapComparer.cs
src/CsvHelper/Configuration/CsvPropertyMapData.cs
src/CsvHelper/ICsvParser.cs
src/CsvHelper/ICsvReader.cs
src/CsvHelper/ICsvReaderRow.cs
src/CsvHelper/ICsvWriter.cs

"that inhererit IEnumerable cannot be auto mapped.". Inherit spelt incorrectly.

Fix typo and remove unused namespaces

---

src/CsvHelper.Tests/CsvWriterTests.cs
src/CsvHelper/CsvWriter.cs

Hi Josh,
I noticed that the latest version of CsvHelper (2.11.0) crashes when the target collection to export is an array.
type.GetGenericTypeDefinition throws InvalidOperationException ("This operation is only valid on generic types.") on non generic interfaces.
In this Pull Request I
- Fixed the CsvWriter.WriteRecords method
- Added WriteEmptyArrayTest
Please let me know if I'm missing something.
Regards,
Dan

Fixed crash on exporting an array.

---

src/CsvHelper/CsvWriter.cs

In a situation where UseExcelLeadingZerosFormatForNumerics = True, and any fields are empty, an IndexOutOfRangeException will be thrown when evaluating " field[0] == '0' ".
Swopped around the logic to test for all digits first, and then if first character is a 0.
Alternatively you could introduce a test for !string.IsNullOrEmpty( field ), although I'm not sure which would be more suitable from a performance perspective?
Thanks.
Stacktrace:
at System.String.get_Chars(Int32 index)
at CsvHelper.CsvWriter.WriteField(String field, Boolean shouldQuote) in c:\Projects\CsvHelper\src\CsvHelper\CsvWriter.cs:line 159
at CsvHelper.CsvWriter.WriteField(String field) in c:\Projects\CsvHelper\src\CsvHelper\CsvWriter.cs:line 140
at CsvHelper.CsvWriter.WriteField(Type type, Object field) in …

CsvWriter.cs: Fix for IndexOutOfRangeException

---

src/CsvHelper.Tests/CsvHelper.Tests.csproj
src/CsvHelper.Tests/CsvReaderReferenceMappingPrefixTests.cs
src/CsvHelper.Tests/CsvWriterReferenceMappingPrefixTests.cs
src/CsvHelper/Configuration/CsvPropertyReferenceMap.cs

Added .Prefix() method to CsvPropertyReferenceMap so that reference
properties could have their fields prefixed if needed.
Note: Initially I used the same style as for PrefixReferenceHeaders in
CsvConfiguration, using the format [Prefix].[FieldName]. However, I
removed the '.' separator as this made it less flexible than simply
allowing the user to determine their own prefix scheme

Feature - Reference prefixes when mapping #270

---

src/CsvHelper.Tests/CsvReaderTests.cs
src/CsvHelper/Configuration/CsvConfiguration.cs
src/CsvHelper/CsvReader.cs

This PR adds a `SkipRecordCallback` property to `CsvConfiguration` that can be set to control which records should be skipped.

Added callback to determine whether to skip a record or not

---

src/CsvHelper.Tests/CsvParserTests.cs
src/CsvHelper/CsvParser.cs

Add Test. Verified all tests are passing.
This may be related to #254.

Fix CsvParser.Row when IgnoreBlank & SkipLines are false

---

index.md

This change fixes an apparent typo in the documentation where QuoteNoFields section shows an example with QuoteAllFields rather than QuoteNoFields.

Fix typo in QuoteNoFields codesample.

---

src/CsvHelper.Tests/Reading/ShouldSkipRecordTests.cs
src/CsvHelper/CsvReader.cs

https://github.com/JoshClose/CsvHelper/issues/575 Setting a Configuration.ShouldSkipRecord method always overrides the Configuration.SkipEmptyRecords setting.
Now if ShouldSkipRecord() returns false and IsRecordEmpty() returns true, the record will be skipped and vice versa

Fixes issue #575

---

src/CsvHelper.Tests/Parsing/PhantomCrTests.cs
src/CsvHelper/CsvParser.cs
src/CsvHelper/FieldReader.cs

Also adds a fix for #677 since it was a 1 line removal and I also ran into it, and it is wrong according to point 2.6 of the CSV RFC @ https://tools.ietf.org/html/rfc4180#section-2
Added a failing test.

Fixes issues caused when \r appears at the end of the FieldReader buffer

---

index.md

Updated docs to remove old `Get<>` method with newer `GetField<>`

Updated docs to remove reference to deprecated method

---

src/CsvHelper.Tests/CsvReaderTests.cs

Empty lines trigger callback ShouldSkipRecord regardless of IgnoreBlankLines = true.
This means one has to handle null (empty row) in callback. The tests demonstrates this.
I suggest to first check IgnoreBlankLines and then raise callback if IgnoreBlankLines is true (which probably means row is never null).
Attached is a test.

ShouldSkipRecord should not require null handling for IgnoreBlankLines true (default)

---

src/CsvHelper.Tests/CsvWriterTests.cs

commit adds WriteInternalConstructorClassTest
This test currently fails because of `internal` constructor (in 3.0.0).
CsvHelper.Configuration.Configuration{ ShouldUseConstructorParameters = type => false } fixes this but should not be necessary for such a simple use case.
Worked before and I think it should work again without special Configuration.

Simple use case with custom class having internal constructor requires special config in 3.0.0

---

src/CsvHelper.Tests/CsvReaderMappingTests.cs

See my last comment #747.
I think the attached test should succeed without removing the commented line.

3.0.0 (RC5 / HEAD): ConvertUsing fails by default when csv file has no field with property name

---

src/CsvHelper.Tests/Parsing/TrimTests.cs

Here is a unit test showing an issue related to #795 
You'll see I have a example of a quoted string with TrimOptions.InsideQuotes, and inside the quoted string I have a delimiter, and it is incorrectly trimming the string in the middle.

Unit test to reproduce bug when using TrimOptions.InsideQuotes

---

src/CsvHelper.Tests/Parsing/TrimTests.cs

This unit test replicates the problem that still happens on 4.0.1 when the buffer has to be read while reading a quoted field. In my real world example, I'm using the default buffer size.

Test showing trim failing with small buffer size

---

src/CsvHelper/CsvReader.cs
src/CsvHelper/IReader.cs

This puzzled me for a bit when it showed up in Visual Studio's autocomplete; I wasn't sure whether this was going to read the whole header record (yep!) or read a single column name from the header record (nope!). This should avoid anyone else experiencing the same confusion.

Fix record vs field confusion in ReadHeader docstring

---

src/CsvHelper.Tests/CsvReaderTests.cs
src/CsvHelper/CsvReader.cs

Modified reader Dispose method so that subsequent calls to Dispose do not throw a NullReferenceException due to context being null.

 Avoid NullReferenceException when reader is Disposed more than once.

---

src/CsvHelper/CsvWriter.cs

- Additional overload for the `CsvWriter` constructors. Fixes #985
- Also fixed docs of an existing overload - should not read `writer`.

Additional convenience constructor

---

src/CsvHelper.Tests/Reading/NullableValuesInEmptyColumnsInputTests.cs
src/CsvHelper.Tests/TypeConversion/TypeConverterOptionsTests.cs
src/CsvHelper/Configuration/Configuration.cs
src/CsvHelper/Configuration/ConfigurationDefaultCallbacks.cs
src/CsvHelper/CsvReader.cs

1. The default callback actions in `Configuration` are lost if the properties are overwritten, preventing consumers from restoring default behaviour if they don't save the delegates first. This PR moves the implementation of those callbacks to a new static class `ConfigurationDefaultCallbacks` so they can always be referenced.
2. This PR fixes issue #1122 where `Configuration.IgnoreBlankLines` was being ignored in the generic `GetField<T>` methods.
Solution builds. All tests pass.

Bugfix for #1122 and now exposes default Configuration callback methods.

---

src/CsvHelper/CsvHelper.csproj

The `PackageReleaseNotes` in `CsvHelper.csproj` file has incorrect value - it does not point to the project's changelog page. This url is presented as one of main NuGet's links, so it's quite important for it to be correct. This PR fixes it. Also, changed scheme from `http` to `https`.

Update PackageReleaseNotes in CsvHelper.csproj

---

src/CsvHelper.Tests/Reading/MappingTypeOfTypeTest.cs
src/CsvHelper/Configuration/ClassMap.cs

This is proposal of fixing issue #1350 
The issue is that when we try to create members for type System.Type, it gives us StackOveflow.
I think it is reasonable to skip any proprety of type System.Type.
There is test for that and fix in line 254:
https://github.com/JoshClose/CsvHelper/pull/1396/commits/dfced9c500ac7abcf1c05866503140e6554662c0#diff-9d8cc792ee1a1d4d7f0a473f09bca1a1R254

Fix reading type System.Type

---

src/CsvHelper/CsvParser.cs
tests/CsvHelper.Tests/Parsing/TrimTests.cs

This fixes #1280 where the first space character inside or at the end of a field is added to the `RawRecord` string twice.

Fix RawRecord adding spaces if TrimOptions.Trim is used

---

src/CsvHelper/Configuration/Attributes/BooleanFalseValuesAttribute.cs
src/CsvHelper/Configuration/Attributes/BooleanTrueValuesAttribute.cs
src/CsvHelper/Configuration/Attributes/ConstantAttribute.cs
src/CsvHelper/Configuration/Attributes/CultureInfoAttribute.cs
src/CsvHelper/Configuration/Attributes/DateTimeStylesAttribute.cs
src/CsvHelper/Configuration/Attributes/DefaultAttribute.cs
src/CsvHelper/Configuration/Attributes/FormatAttribute.cs
src/CsvHelper/Configuration/Attributes/HeaderPrefixAttribute.cs
src/CsvHelper/Configuration/Attributes/IMemberMapper.cs
src/CsvHelper/Configuration/Attributes/IMemberReferenceMapper.cs
src/CsvHelper/Configuration/Attributes/IgnoreAttribute.cs
src/CsvHelper/Configuration/Attributes/IndexAttribute.cs
src/CsvHelper/Configuration/Attributes/NameAttribute.cs
src/CsvHelper/Configuration/Attributes/NameIndexAttribute.cs
src/CsvHelper/Configuration/Attributes/NullValuesAttribute.cs
src/CsvHelper/Configuration/Attributes/NumberStylesAttribute.cs
src/CsvHelper/Configuration/Attributes/TypeConverterAttribute.cs
src/CsvHelper/Configuration/ClassMap.cs

Hi @JoshClose ,
I did a minor refactoring to enhance the configuration process using attributes.
With this enhancement:
1.  Two new interfaces are introduced (````IMemberMapper```` and ````IMemberReferenceMapper````).
2.  The mapping attributes were tagged with the appropriate interfaces.
3.  The mapping logic was moved out of ````ClassMap```` into the corresponding class.
4.  ````ClassMap```` was refactored to call the interface method instead of having a hard-coded set of mappings.
This will allow developers to extend/customize the process by simply creating their own custom ````Attribute```` that implements ````IMemberMapper```` or ````IMemberReferenceMapper````.
Would you please let me know what we need to do to get this change committed?
Thanks so much!

Updates to enable custom mappings using attributes.

---

src/CsvHelper/Expressions/ObjectRecordWriter.cs
tests/CsvHelper.Tests/CsvWriterMappingTests.cs

Should fix issues #1454 and #1595.
`ConvertUsing` now is allowed to return `null` which will result in empty field.

Convert using null issue 1595 / 1454

---

src/CsvHelper/CsvDataReader.cs

fix: support ignore case search for GetOrdinal

---

src/CsvHelper/CsvDataReader.cs
tests/CsvHelper.Tests/DataTableTests/CsvDataReaderTests.cs

- `CsvHelper.CsvDataReader.get_FieldCount()` is throwing `System.NullReferenceException` if you try to read from an empty file.
- Fixes #1508

Empty CSV file passed to CsvDataReader

---

src/CsvHelper/CsvReader.cs
src/CsvHelper/CsvWriter.cs
src/CsvHelper/IReader.cs
src/CsvHelper/IWriter.cs
tests/CsvHelper.Tests/Async/ReadingTests.cs
tests/CsvHelper.Tests/Async/WritingTests.cs

Exposed on writer/reader primary calls
Only flows down to the big while loop, as nothing else was interruptible
Adds reader/writer tests.
Added with explicit defaults on the interface to help not break existing.
#1359

Adds cancelation to async methods

---

tests/CsvHelper.Tests/Culture/TypeConverterOptionsFactoryTests.cs
tests/CsvHelper.Tests/LocalCultureTests.cs
tests/CsvHelper.Tests/TypeConversion/TypeConverterOptionsFactoryTests.cs

Linux and macOS use the International Components for Unicode (ICU) libraries for globalization functionality. This is also true for [.NET 5 when running on Windows 10 May 2019 Update or later][1].
ICU and [National Language Support (NLS)][2] (which is used in .NET Core 1.0 - 3.1 and .NET Framework 4 and later on Windows) have slightly different behaviors.
This commit adresses these discrepancies by:
* Using explicit `N2` format instead of `N` to ensure two decimals formatting in `CsvHelper.Tests.Culture.TypeConverterOptionsFactoryTests.WriteRecordsAppliedWhenMappedTest` and `CsvHelper.Tests.TypeConversion.TypeConverterOptionsFactoryTests.WriteRecordsAppliedWhenMappedTest`.
* Choosing a date which formats the same with ICU and NLS under the `uk-UA` culture. The previous date (`new …

Fix culture-sensitive tests

---

src/CsvHelper/CsvDataReader.cs

IDataReader maps between the input source and the destination table using the schema details provided by GetSchemaTable(). Currently in CsvDataReader all columns are defaulted to strings which causes conversion issues when using as a source for SqlBulkCopy.
To remedy this I have added an additional constructor that accepts a DataTable along with the required CsvReader, this DataTable should contain the schema of the destination table and can be generated like so.
```
public static DataTable GetDataTableSchema(string schema, string tableName)
{
DataTable dataTable = new DataTable();
using (SqlConnection _sqlConnection = new SqlConnection(_sqlConnectionString))
using (SqlCommand command = new SqlCommand("select top 0 * from " + schema + "." + tableName))
{
command.Connection = …
```

Allow schema of destination table to be specified in CsvDataReader constructor

---

src/CsvHelper/Configuration/IParserConfiguration.cs

[\t was removed from WhiteSpaceChars](https://github.com/JoshClose/CsvHelper/commit/72cad999ee043814e67e42b1c3095e7f648d943a), so the property's summary should be updated to remove the same.

Update WhiteSpaceChars summary

---

src/CsvHelper/CsvParser.cs
tests/CsvHelper.Tests/CsvReaderTests.cs
tests/CsvHelper.Tests/Issues/Issue1954.cs
tests/CsvHelper.Tests/Mappings/ConstructorParameter/CultureInfoAttributeTests.cs
tests/CsvHelper.Tests/Mappings/ConstructorParameter/CultureInfoMapTests.cs
tests/CsvHelper.Tests/Mappings/ConstructorParameter/DateTimeStylesAttributeTests.cs
tests/CsvHelper.Tests/Mappings/ConstructorParameter/DateTimeStylesMapTests.cs
tests/CsvHelper.Tests/Writing/MultipleFieldsFromOnePropertyTests.cs

Although I have only a superficial understanding of how the parser works, I think I found the reason for issue #1954: The information on whether the parser is at the begin of a field is not preserved throughout multiple calls to `ReadLine` in this case. Therefore, if the buffer is re-filled and `ReadLine` is called again, it does not know any more that between the begin of the field and the current position were only white spaces.
I believe that moving the `fieldStartPosition` to the buffer position at the last whitespace that was skipped will transport this information to the next invocation. This PR adds this fix and provides a test case for the issue.

Test and fix for #1954

---

src/CsvHelper.Website/input/examples/configuration/class-maps/mapping-by-index/index.md

issue #2016 
CsvConfiguration parameter was not passed in the CsvReader constructor in [mapping by index](https://joshclose.github.io/CsvHelper/examples/configuration/class-maps/mapping-by-index/) docs example.

Pass configuration in the CsvReader constructor

---

docs/getting-started/index.html
src/CsvHelper.Website/input/getting-started/index.md

Link currently sends to [https://joshclose.github.io/CsvHelper/api/CsvHelper.Configuration.Attributes](https://joshclose.github.io/CsvHelper/api/CsvHelper.Configuration.Attributes) instead of to [https://joshclose.github.io/CsvHelper/examples/configuration/attributes/](https://joshclose.github.io/CsvHelper/examples/configuration/attributes/)

Fix broken link

---

docs/change-log/index.html
docs/migration/v27/index.html
src/CsvHelper.Website/input/change-log/index.md
src/CsvHelper.Website/input/migration/v27/index.md

Fixed two small issues in the 26 to 27 migration documentation:
* Fixed a typo: `CsvConfiugration` -> `CsvConfiguration`
* Used the correct propertyname: `WhiteSpaceCharacters` -> `WhiteSpaceChars`. See [here](https://github.com/JoshClose/CsvHelper/blob/9137bde39ccfe1423981bfa8883cc18f24a26412/src/CsvHelper/Configuration/CsvConfiguration.cs#L159) for the code.

Fix 26 to 27 migration doc

---

src/CsvHelper/Configuration/MemberMap.cs
tests/CsvHelper.Tests/Reading/ValidateTests.cs

This matches the type in MemeberMap`1's function, now that the string is a property within the ValidateArgs class.  Fixes the (unreported?) error "Expression of type string cannot be used for parameter of type ValidateArgs".

Update Validate's expression param to ValidateArgs

---

src/CsvHelper/CsvReader.cs
tests/CsvHelper.Tests/CsvReaderTests.cs
tests/CsvHelper.Tests/Exceptions/ExceptionMessageTests.cs
tests/CsvHelper.Tests/Reading/NullableValuesInEmptyColumnsInputTests.cs

Previously MissingFieldFound wasn't called in GetField when IgnoreBlankLines was set to false.
I think it's at least misleading / some configuration settings produce unexpected results.
The goal of this PR is to get clear behavior:
Always throw exception if GetField is called on non-existing field unless suppressed via MissingFieldFound.
IgnoreBlankLines should only skip those rows while reading.

Getfield should throw errors on missing fields (as long as not suppressed)

---

src/CsvHelper/CsvReader.cs
src/CsvHelper/Expressions/ExpressionManager.cs

The same array is allocated twice. Re-used the first one.

Reduce array allocations

---

src/CsvHelper/Configuration/ClassMapCollection.cs
src/CsvHelper/CsvReader.cs
src/CsvHelper/TypeConversion/EnumConverter.cs

Each dictionary lookup requires hash calculation and iteration over bucket and match of item. Puropse of existence `TryGetValue` in Dictionary class is to reduce double lookup to improve performance.

Reduce double dictionary lookup in CsvReader.ParseNamedIndexes()

---

src/CsvHelper/CsvWriter.cs

Using Entity Framework Core, I am getting a List<object> which I am passing to WriteRecords. One record is null and WriteRecords throws an object reference  exception. I added a check for null and everything works correctly now.

Add null check for WriteRecords

---

src/CsvHelper/Configuration/MemberReferenceMapData.cs
tests/CsvHelper.Tests/AttributeMapping/HeaderPrefixTests.cs

For complex object graph or an object with multiple properties referencing a same type, it may be useful to nest header prefix.
```
class A
[HeaderPrefix("B1")]
public B B
[HeaderPrefix("B2")]
public B B
[HeaderPrefix("B3")]
public B B
class B
[HeaderPrefix("Name")]
public C C
class C
public int ID {get; set;}
```
So that the csv header is set to B1.Name.ID, B2.Name.ID, B3.Name.ID respectively.

allow inherited prefix headers

---

src/CsvHelper/Configuration/ClassMap`1.cs

String interpolation was not set on the InvalidOperationException error message being thrown so no context of the value of 'expression' was provided.

Fix printing '{expression}' using interpolation

---

src/CsvHelper/TypeConversion/DefaultTypeConverter.cs

Hi,
when we get a conversion error in a file with many coulmns it's impossibile to understand where the error comes from, just adding the property name points directly to the problem.

add member name in  TypeConverterException message

---

tests/CsvHelper.Tests/TypeConversion/TypeConverterTests.cs

This is a failing test.
Seems the problem has to do with the usage of an anonymous type where Uri is a constructor parameter type.
Perhaps `AutoMap` is building a map that can be used to read, too -- but we need just a `IWriterConfiguration`.
Finally using Uri type results in some StackOverflow exception (but I hoped `MyUriConverter` would avoid this).

adds a test showing that a custom typeconverter for Uri fails

---

src/CsvHelper.Tests/Parsing/MaxFieldSizeTests.cs
src/CsvHelper/Configuration/Configuration.cs
src/CsvHelper/Configuration/IParserConfiguration.cs
src/CsvHelper/CsvParser.cs
src/CsvHelper/MaxFieldSizeException.cs

Sometimes our customers deliver an invalid csv file containing a long record with \0 characters. Too prevent reading the file until either the end of file is reached or an OutOfMemoryException occurs (by resizing the field buffer) we introduced a MaxFieldSize property. When the max field size property is configured, the reader aborts further reading when the field length exceeds the configured maximum.

Fail on reading large fields

---

README.markdown

Added clickable NuGet badges to the README so that users can quickly navigate to the NuGet page as well as see what the current published version is on NuGet and the total download count.

Add clickable NuGet badges to README

---

src/CsvHelper/CsvWriter.cs

The field leaveOpen is not assigned in the CsvWriter constructor
fix #2066

fix(CsvWriter): fix 'leaveOpen' parameter does not work

---

src/CsvHelper/TypeConversion/DateOnlyConverter.cs
src/CsvHelper/TypeConversion/TimeOnlyConverter.cs
src/CsvHelper/TypeConversion/TypeConverterCache.cs
tests/CsvHelper.Tests/TypeConversion/DateOnlyConverterTests.cs
tests/CsvHelper.Tests/TypeConversion/TimeOnlyConverterTests.cs

If support is ever added for .NET 7 or later, this will ensure support for these classes is still compiled in. These preprocessor symbols are [documented here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives).

Use NET6_0_OR_GREATER to detect support for DateOnly and TimeOnly

---

src/CsvHelper/Configuration/ConfigurationFunctions.cs

fix for https://github.com/JoshClose/CsvHelper/issues/2202
there is an invalid loop which causes the header to be printed for header.length

remove-invalid-loop

---

src/CsvHelper/Configuration/ConfigurationFunctions.cs

This PR moves the space checks before the quote check & moves new line checks before the delimiter check. While it will definitely depend on the input data, this change sorting the comparisons from fastest to potentially the slowest one should help with the performance.

Change order of checks in default ShouldQuote implementation

---

src/CsvHelper/TypeConversion/CollectionConverterFactory.cs

Fixes #2081 Fixes #2069
Fixes "This Operation is only valid on generic types." error caused by calling type.GetGenericTypeDefinition on non generic types.

Fixes #2081

---

src/CsvHelper/Expressions/ObjectRecordWriter.cs
tests/CsvHelper.Tests/Issues/Issue2118.cs

When the parameterless `Map()` (returning `MemberMap<object, object>`) is used in combination with `Convert(ConvertToString<TClass>)` then `TClass` is `object` but when writing we invoke the delegate with a `ConvertToStringArgs<T>` where `T` is the type of the record and not `object`. This fails because `TClass` is invariant on the `ConvertToString` delegate (we cannot express it as contravariant, I think because of the generic struct argument). So we need to construct the `ConvertToStringArgs` with the same generic type as that of the `ConvertToString` delegate stored in `WritingConvertExpression`.
fixes #2118

Ensure the ConvertToStringArgs are constructed with the correct generic type

---

src/CsvHelper/CsvParser.cs
src/CsvHelper/CsvReader.cs
tests/CsvHelper.Tests/Issues/Issue1341.cs

...rather than later during field processing. When reading a line break in a quoted field with `LineBreakInQuotedFieldIsBadData = true`, the previous implementation consumes data indefinitely until another quote is found.
This is undesirable considering that setting `LineBreakInQuotedFieldIsBadData = true` implies that a line break should be considered the end of the record, which it now is.
fixes #1341, #2152

Deal with line break in quoted field during Read

---

.gitignore
src/CsvHelper/TypeConversion/NotSupportedTypeConverter.cs
src/CsvHelper/TypeConversion/TypeConverter.cs
src/CsvHelper/TypeConversion/TypeConverterCache.cs
src/CsvHelper/TypeConversion/TypeConverterGeneric.cs
tests/CsvHelper.Tests/TypeConversion/TypeConverterFactoryTests.cs

See https://github.com/JoshClose/CsvHelper/issues/2153
Notes: I added a new abstract TypeConverterGeneric<T> class to make it easier to create generic type converters.
This is not necessary to fix the issue, but makes it a easier to write generic type converter factories (as can be seen in test).
Please have a look at System.Text.Json.Serialization.JsonConverter<T> (and JsonConverterFactory) which has this and is a quite useful API. I recommend to rename `TypeConverterGeneric<T>` to `TypeConverter<T>` to make it consistent (see again `JsonConverter`) but this name is already taken without `<T>` for something different. I will add another commit to solve this but of course this is a (minor) breaking change as current `TypeConverter` is public (but probably not used by anyone). Please feel …

Fix 2153 TypeConverterFactory not used

---

src/CsvHelper/TypeConversion/GuidConverter.cs
tests/CsvHelper.Tests/TypeConversion/GuidConverterTests.cs

GuidConverter should be consistent with other value converters.
When an Integer cannot be parsed from a source Csv, using the `Int32Converter`, a `TypeConverterException` is thrown;
When Guid's cannot be parsed from a source Csv, using the `GuidConverter`, a `FormatException` is thrown.
This is to provide a consistent behaviour with other base converters.

🔨 GuidConverter should be consistent

---

src/CsvHelper/Configuration/ClassMap.cs
src/CsvHelper/Configuration/CsvConfiguration.cs
src/CsvHelper/ReflectionHelper.cs

Instead of retrieving an attribute _only_ to see if it exists we can use `Attribute.IsDefined` for this.
Here's a micro benchmark to show that `GetCustomAttributes`+`Any` allocates 104 bytes while `IsDefined` is allocation free.
| Method              | Mean     | Error   | StdDev  | Ratio | Gen0   | Allocated | Alloc Ratio |
|-------------------- |---------:|--------:|--------:|------:|-------:|----------:|------------:|
| GetCustomAttributes | 243.6 ns | 0.94 ns | 0.83 ns |  1.00 | 0.0124 |     104 B |        1.00 |
| IsDefined           | 139.6 ns | 0.55 ns | 0.51 ns |  0.57 |      - |         - |        0.00 |
<details>
<summary>benchmark code</summary>
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Reflection;
using System.Runtime.CompilerServices; …
```

Use `IsDefined` to check the presence of attributes

---

src/CsvHelper/ObjectCreator.cs

This is a candidate fix for https://github.com/JoshClose/CsvHelper/issues/2315
The implementation of Dictionary will use hash codes under the hood, but handle collisions correctly.
By using a hashcode for the dictionary key the existing code prevents the .NET class from doing the right thing.
Notes:
This may degrade performance because cache hits need to do the full Equals call to verify that it is not a hash collision.
This may degrade performance because of changes in inlining behavior.

Use a CacheKey struct for the ObjectCreator cache

---

src/CsvHelper.Website/input/change-log/index.md
src/CsvHelper/CsvWriter.cs

We should check enumerator with `IAsyncDisposable` too.
p.s. A bit better version of https://github.com/JoshClose/CsvHelper/pull/2265
Closes: https://github.com/JoshClose/CsvHelper/issues/2264

fix: dispose enumerator in CsvWriter.WriteRecordsAsync

---

src/CsvHelper/TypeConversion/DefaultTypeConverter.cs
tests/CsvHelper.Tests/Mocks/ReaderRowMock.cs
tests/CsvHelper.Tests/TypeConversion/NullableConverterTests.cs

Setting `null` as the default value for a member with a nullable type with `UseDefaultOnConversionFailure` set to `true` will not use that default value when a conversion failure occurs, but throws a `TypeConverterException` instead. This is unintuitive behavior and seems like a bug.
This code fixes the type comparison when the default value is set to `null` so that the code behaves like one would expect.
[discussion](https://github.com/JoshClose/CsvHelper/issues/2156#issuecomment-2245023237)
Closes #2156

Fix UseDefaultOnConversionFailure behavior for nullable types

---

docs/examples/configuration/class-maps/mapping-by-name/index.html

There is no function RegisterClassMap in the class Context so I searched for and find that it must be called "Configuration".
The full error message in Unity: 
error CS1061: 'ReadingContext' does not contain a definition for 'RegisterClassMap' and no accessible extension method 'RegisterClassMap' accepting a first argument of type 'ReadingContext' could be found.

fix (typo?): error CS1061 function in class not found

---

docs/examples/configuration/class-maps/validation/index.html

Updating the Validate documentation:
.Validate(field.=> !field.Contains("-"));
To:
.Validate(item => !item.Field.Contains("-"));

Updating Validate

---

tests/CsvHelper.Tests/Reading/NumberReadingTests.cs

I just had to locate a bug regarding decimal number parsing (decimal separator issue).
CsvHelper is working fine, but I wrote a simple test to rule out the possibility for a library issue. 
Bug was on my side (wrong culture given in user code).
Maybe you like to add this test safeguarding this use case -- maybe not.

Just another unit test for number reading (mixed culture format)
